Repository AY2122S2-CS2103T-W14-2/tp, pull requests merged in 2022-04, with the labels that each got.

#142 Implemented test cases for sort tasks by date
  src/test/java/seedu/address/logic/commands/SortTaskByDateCommandTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task

#206 Fix the special character in player name bug
  src/main/java/seedu/address/logic/commands/strategy/AddPlayerCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/strategy/AddPlayerCommandParser.java
  src/main/java/seedu/address/model/strategy/Player.java
Labels: bug

#209 Update the UG to reflect the player name constraints
  docs/UserGuide.md
Labels: documentation

#211 Fix note related documentation bugs v1.4
  docs/UserGuide.md
Labels: Documentation Bug

#212 Fix documentation bugs
  docs/UserGuide.md
Labels: Documentation Bug

#215 Update personal PPP
  docs/team/simjunheng.md
Labels: documentation

#219 Fix case insensitive note bug
  src/main/java/seedu/address/model/note/Note.java
  src/test/java/seedu/address/model/note/NoteTest.java
Labels: bug

#218 Error Message not shown in Find Person and Find Task Command
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: Review Needed, Functionality Bug

#216 Fix sort-date wiping all taskbook data
  src/main/java/seedu/address/logic/commands/SortTaskByDateCommand.java
Labels: bug

#143 Implemented test cases for delete tasks from tag
  src/main/java/seedu/address/logic/parser/DeleteTagFromTaskCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteTagFromTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagFromTaskCommandParserTest.java
Labels: type.Task

#221 Fix courts directory not generating and fix related documentation bugs
  courts/basketball.png
  courts/soccer.png
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/test/java/seedu/address/testutil/TestImageCreator.java
Labels: bug, Documentation Bug

#220 Update personal PPP
  docs/team/rye-catcher.md
Labels: documentation

#140 Update DG with sort tasks by date command
  docs/DeveloperGuide.md
Labels: documentation

#214 Add "About the User Guide" section into UG
  docs/UserGuide.md
Labels: documentation, Review Needed

#223 Add Assigned Features in implementation section (DG)
  docs/DeveloperGuide.md
  docs/diagrams/AddPersonSequenceDiagram.puml
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/ClearPersonSequenceDiagram.puml
  docs/diagrams/DeletePersonSequenceDiagram.puml
  docs/diagrams/DeleteTaskSequenceDiagram.puml
  docs/diagrams/EditPersonSequenceDiagram.puml
  docs/diagrams/EditTaskSequenceDiagram.puml
  docs/diagrams/FindPersonSequenceDiagram.puml
  docs/diagrams/FindTaskSequenceDiagram.puml
  docs/diagrams/GetPersonSequenceDiagram.puml
  docs/images/AddPersonSequenceDiagram.png
  docs/images/AddTaskSequenceDiagram.png
  docs/images/ClearPersonSequenceDiagram.png
  docs/images/DeletePersonSequenceDiagram.png
  docs/images/DeleteTaskSequenceDiagram.png
  docs/images/EditPersonSequenceDiagram.png
  docs/images/EditTaskSequenceDiagram.png
  docs/images/FindPersonSequenceDiagram.png
  docs/images/FindTaskSequenceDiagram.png
  docs/images/GetPersonSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation, Review Needed

#229 Bugfix for #113
  src/main/java/seedu/address/logic/parser/person/AddPersonTagCommandParser.java
  src/main/java/seedu/address/logic/parser/person/DeletePersonTagCommandParser.java
  src/main/java/seedu/address/logic/parser/task/AddTaskTagCommandParser.java
  src/main/java/seedu/address/logic/parser/task/DeleteTaskTagCommandParser.java
  src/test/java/seedu/address/testutil/TestImageCreator.java
Labels: type.Bug

#231 export-command testcase
  src/test/java/seedu/address/logic/commands/strategy/ExportCommandTest.java
Labels: type.Task

#230 add-task bug fix
  src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/EditTaskCommand.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/task/EditTaskCommandTest.java
Labels: type.Task

#237 Add signposting to command summary section in UG
  docs/UserGuide.md
Labels: documentation

#235 Fix clear task bug v1.4
  src/main/java/seedu/address/logic/commands/task/ClearTaskCommand.java
Labels: bug

#232 Implement Assigned UG/DG changes for v1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/diagrams/AddNoteSequenceDiagram.puml
  docs/diagrams/DeleteNoteSequenceDiagram.puml
  docs/diagrams/LoadCourtSequenceDiagram.puml
  docs/diagrams/SortNoteSequenceDiagram.puml
  docs/images/AddNoteSequenceDiagram.png
  docs/images/DeleteNoteSequenceDiagram.png
  docs/images/LoadCourtSequenceDiagram.png
  docs/images/SortNoteSequenceDiagram.png
  docs/images/Ui-Labeled.png
  docs/team/aalghrairy.md
  docs/team/johndoe.md
Labels: documentation

#243 Update move player feature to support relative positions
  src/main/java/seedu/address/model/strategy/Player.java
  src/main/java/seedu/address/ui/StrategyPanel.java
Labels: bug

#240 Update DG (Xiaoteng)
  docs/DeveloperGuide.md
  docs/diagrams/AddPlayerSequenceDiagram.puml
  docs/diagrams/DeletePlayerSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/MovePlayerSequenceDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/AddPlayerSequenceDiagram.png
  docs/images/DeletePlayerSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/MovePlayerSequenceDiagram.png
  docs/images/ParserClasses.png
Labels: documentation

#245 Add Instructions for Manual Testing features
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#247 Fix the position of move player
  src/main/java/seedu/address/ui/StrategyPanel.java
Labels: bug

#253 Add tutorial for move feature
  docs/UserGuide.md
  docs/images/move-ex1.png
  docs/images/move-ex2.png
Labels: documentation

#252 Edits made to the UG
  docs/UserGuide.md
Labels: documentation

#248 Add testing cases for strategy board related classes
  src/test/java/seedu/address/logic/commands/strategy/AddPlayerCommandTest.java
  src/test/java/seedu/address/logic/commands/strategy/DeletePlayerCommandTest.java
  src/test/java/seedu/address/logic/commands/strategy/MovePlayerCommandTest.java
  src/test/java/seedu/address/model/strategy/PlayerTest.java
Labels: type.Task

#258 Re-push the test case adding
  src/test/java/seedu/address/logic/commands/strategy/AddPlayerCommandTest.java
  src/test/java/seedu/address/logic/commands/strategy/DeletePlayerCommandTest.java
  src/test/java/seedu/address/logic/commands/strategy/MovePlayerCommandTest.java
  src/test/java/seedu/address/model/strategy/PlayerTest.java
Labels: type.Task

#251 Player coord constraints
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/strategy/MovePlayerCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/strategy/MovePlayerCommandParser.java
  src/main/java/seedu/address/model/strategy/Player.java
Labels: bug

#264 Update personal PPP
  docs/team/rye-catcher.md
Labels: documentation

#265 Fix reference link bug in DG
  docs/DeveloperGuide.md
Labels: Documentation Bug
