Repository AY2122S2-CS2103T-W14-2/tp, pull requests merged in 2022-03, with the labels that each got.

#25 More updates to UserGuide.md
  docs/UserGuide.md
Labels: documentation

#30 Week7 Developer Guide: Add use case for <Add a tag to a person>
  docs/DeveloperGuide.md
Labels: documentation

#29 Add "add person" use case
  docs/DeveloperGuide.md
Labels: documentation

#31 DeveloperGuide.md updated with 'Delete tag from person' use-case
  docs/DeveloperGuide.md
Labels: documentation

#32 Edit DeveloperGuide.md to fix formatting errors
  docs/DeveloperGuide.md
Labels: documentation

#37 Add tab-pane into GUI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: enhancement, Attention Needed

#47 Fix the white blank area in full screen GUI
  src/main/resources/view/MainWindow.fxml
Labels: bug

#38 As a forgetful coach I can enter team-specific or player notes so that information will not be forgotten
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/ListUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, Attention Needed

#53 Implement TaskCard and TaskListPanel GUI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskCard.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: enhancement

#55 Add testing methods for AddNoteCommand
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddNoteCommandParserTest.java
  src/test/java/seedu/address/model/note/NoteTest.java
Labels: type.Task

#48 Implement the note-del feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: enhancement, Attention Needed

#60 Reimplement note-del feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: enhancement

#61 Implement drag and move features in StrategyPanel
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StrategyPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StrategyPanel.fxml
Labels: type.Task

#57 Implement tag-add and tag-del feature
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
Labels: enhancement

#56 Implement Add-task and delete-task feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/EndTime.java
  src/main/java/seedu/address/model/task/StartTime.java
Labels: enhancement

#65 Add tests for add-task and delete-task commands
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task

#80 Enable assertions in build.gradle
  build.gradle
Labels: type.Task

#76 Tag Persons to Task
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/EditTaskDescriptor.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedName.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TaskCard.fxml
  src/test/data/JsonSerializableTaskBookTest/typicalTasksTaskBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: enhancement, type.Story

#78 Implement clear tasks function
  src/main/java/seedu/address/logic/commands/ClearTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearTaskCommandParser.java
  src/test/java/seedu/address/logic/commands/ClearTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClearTaskCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: enhancement

#88 Update command format to match UG
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Task

#83 Individual documentation update for v1.3
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/team/aalghrairy.md
Labels: documentation

#86 Developer & User Guide Updates (Jun Heng)
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/FindPersonSequenceDiagram.png
Labels: documentation

#89 Fix minor issue in UG
  docs/UserGuide.md
Labels: documentation

#91 Update find person sequence diagram
  docs/diagrams/FindPersonSequenceDiagram.puml
  docs/images/FindPersonSequenceDiagram.png
Labels: documentation

#93 Implement load court v1.3
  courts/basketball.png
  courts/soccer.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/LoadCourtCommand.java
  src/main/java/seedu/address/logic/commands/notecommands/AddMiscCommand.java
  src/main/java/seedu/address/logic/commands/notecommands/AddStrengthCommand.java
  src/main/java/seedu/address/logic/commands/notecommands/AddWeaknessCommand.java
  src/main/java/seedu/address/logic/commands/notecommands/DeleteMiscCommand.java
  src/main/java/seedu/address/logic/commands/notecommands/DeleteStrengthCommand.java
  src/main/java/seedu/address/logic/commands/notecommands/DeleteWeaknessCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/LoadCourtCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ReadOnlyStrategyBoard.java
  src/main/java/seedu/address/model/image/Image.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StrategyPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StrategyPanel.fxml
  src/test/java/seedu/address/logic/commands/LoadCourtCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/LoadCourtCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/image/ImageTest.java
  src/test/java/seedu/address/testutil/TestImageCreator.java
Labels: enhancement

#104 AddTagCommand functionality update
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
Labels: enhancement

#105 DeleteTagCommand functionality update
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
Labels: enhancement

#94 Documentation details update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/images/AddTaskSequenceDiagram.png
Labels: documentation

#96 Juay hee ugdg update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddTagSequenceDiagram.puml
  docs/images/AddTagSequenceDiagram.png
Labels: documentation

#85 Implements add and delete players in Strategy Panel feature
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/strategy/AddPlayerCommand.java
  src/main/java/seedu/address/logic/commands/strategy/DeletePlayerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/strategy/AddPlayerCommandParser.java
  src/main/java/seedu/address/logic/parser/strategy/DeletePlayerCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/StrategyBoard.java
  src/main/java/seedu/address/model/strategy/UniquePlayerList.java
  src/main/java/seedu/address/model/strategy/exceptions/DuplicatePlayerException.java
  src/main/java/seedu/address/model/strategy/exceptions/PlayerNotFoundException.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StrategyPanel.java
  src/main/resources/view/StrategyPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMiscCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStrengthCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/AddWeaknessCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteMiscCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStrengthCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteWeaknessCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/LoadCourtCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Story, type.Enhancement

#97 Edit clear person command to support person tagging to tasks
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Enhancement, Review Needed

#100 As a coach, I can quickly get the information of all contacts tagged to a specific task so that time is saved on contact retrieval
  src/main/java/seedu/address/commons/core/Tabs.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/GetPersonCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/LoadCourtCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/GetPersonCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonSerializableTaskBookTest/typicalTasksTaskBook.json
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/GetPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/GetPersonCommandParserTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: enhancement, type.Story, Review Needed

#115 Fix add-note bug
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/notecommands/AddMiscCommand.java
  src/main/java/seedu/address/logic/commands/notecommands/AddStrengthCommand.java
  src/main/java/seedu/address/logic/commands/notecommands/AddWeaknessCommand.java
  src/test/java/seedu/address/logic/commands/AddMiscCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStrengthCommandTest.java
  src/test/java/seedu/address/logic/commands/AddWeaknessCommandTest.java
Labels: bug

#124 Feature: Sort tasks by date
  src/main/java/seedu/address/logic/commands/SortTaskByDateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/task/Date.java
  src/main/java/seedu/address/model/task/Task.java
Labels: enhancement

#106 Implements ruler for strategy panel
  src/main/java/seedu/address/ui/StrategyPanel.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/StrategyPanel.fxml
Labels: enhancement, Review Needed

#122 Implement move player feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/strategy/AddPlayerCommand.java
  src/main/java/seedu/address/logic/commands/strategy/DeletePlayerCommand.java
  src/main/java/seedu/address/logic/commands/strategy/MovePlayerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/strategy/MovePlayerCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyStrategyBoard.java
  src/main/java/seedu/address/model/StrategyBoard.java
  src/main/java/seedu/address/model/strategy/Player.java
  src/main/java/seedu/address/model/strategy/UniquePlayerList.java
  src/main/java/seedu/address/ui/StrategyPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, Review Needed

#116 Implement sort-strength and sort-weakness features
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/SortStrengthCommand.java
  src/main/java/seedu/address/logic/commands/SortWeaknessCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/SortStrengthCommandTest.java
  src/test/java/seedu/address/logic/commands/SortWeaknessCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, Review Needed

#135 Updated Edit task command
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/model/TaskBook.java
  src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/EditTaskCommandParserTest.java
Labels: enhancement, type.Story, Review Needed

#136 Additional testcase for Edit-task person field
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java
Labels: type.Task

#133 Individual Documentation update for v1.3b
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/aalghrairy.md
Labels: documentation

#137 Implement export command
  build.gradle
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/GetPersonCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/LoadCourtCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StrategyPanel.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/GetPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: enhancement, type.Story

#129 Feature: Delete tags from tasks
  src/main/java/seedu/address/logic/commands/DeleteTagFromTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagFromTaskCommandParser.java
Labels: enhancement

#141 Update UG with sort task by date details
  docs/UserGuide.md
Labels: documentation

#139 Update UGDG with assigned features
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, Review Needed

#144 Update index.md
  README.md
  docs/images/Ui.png
  docs/index.md
Labels: documentation
